var tagValues = [
  ["Kn611", "Lists of Personnel"],
  ["Kn612", "Lists of Personnel"],
  ["Kn624", "Lists of Personnel"],
  ["Kn627", "Lists of Personnel"],
  ["Kn616", "Lists of Personnel"],
  ["Kn784", "Lists of Personnel"],
  ["Kn618", "Lists of Personnel"],
  ["Kn739", "Lists of Personnel"],
  ["Kn824", "Lists of Personnel"],
  ["Kn827", "Lists of Personnel"],
  ["Kn63", "Lists of Personnel"],
  ["Kn601", "Lists of Personnel"],
  ["Kn819", "Lists of Personnel"],
  ["Kn609", "Lists of Personnel"],
  ["Kn1516", "Lists of Personnel"],
  ["Kn1517", "Lists of Personnel"],
  ["Py62", "Lists of Personnel"],
  ["Py240", "Lists of Personnel"],
  ["Py717", "Lists of Personnel"],
  ["Py792", "Lists of Personnel"],
  ["Py379", "Lists of Personnel"],
  ["Py553", "Lists of Personnel"],
  ["Py670", "Lists of Personnel"],
  ["Py676", "Lists of Personnel"],
  ["Py671", "Lists of Personnel"],
  ["Py697", "Lists of Personnel"],
  ["Py684", "Lists of Personnel"],
  ["Py686", "Lists of Personnel"],
  ["Py292", "Lists of Personnel"],
  ["Py694", "Lists of Personnel"],
  ["Py303", "Lists of Personnel"],
  ["Py607", "Lists of Personnel"],
  ["Py264", "Lists of Personnel"],
  ["Py134", "Lists of Personnel"],
  ["Py261", "Lists of Personnel"],
  ["Py35", "Lists of Personnel"],
  ["Py1277", "Lists of Personnel"],
  ["Py1280", "Lists of Personnel"],
  ["Py830", "Lists of Personnel"],
  ["Py1281", "Lists of Personnel"],
  ["My659", "Lists of Personnel"],
  ["My102", "Lists of Personnel"],
  ["Kn821", "Lists of Personnel"],
  ["Kn822", "Lists of Personnel"],
  ["Kn826", "Lists of Personnel"],
  ["Kn101", "Lists of Personnel"],
  ["Kn997", "Lists of Personnel"],
  ["Kn913", "Lists of Personnel"],
  ["Kn941", "Lists of Personnel"],
  ["Kn1180", "Lists of Personnel"],
  ["Kn895", "Lists of Personnel"],
  ["Kn902", "Lists of Personnel"],
  ["Kn59", "Lists of Personnel"],
  ["Kn896", "Lists of Personnel"],
  ["Kn907", "Lists of Personnel"],
  ["Py427", "Lists of Personnel"],
  ["Py39", "Lists of Personnel"],
  ["Py18", "Lists of Personnel"],
  ["Py207", "Lists of Personnel"],
  ["Py1282", "Lists of Personnel"],
  ["Py1", "Lists of Personnel"],
  ["Py610", "Lists of Personnel"],
  ["Py724", "Lists of Personnel"],
  ["Py657", "Lists of Personnel"],
  ["Py654", "Lists of Personnel"],
  ["Py519", "Lists of Personnel"],
  ["Py656", "Lists of Personnel"],
  ["Py661", "Lists of Personnel"],
  ["Py3", "Lists of Personnel"],
  ["Py418", "Lists of Personnel"],
  ["Py1287", "Lists of Personnel"],
  ["Py131", "Livestock"],
  ["Py655", "Livestock"],
  ["Py719", "Livestock"],
  ["Py660", "Livestock"],
  ["Kn1221", "Livestock"],
  ["Kn1232", "Livestock"],
  ["Kn1129", "Livestock"],
  ["Kn1171", "Livestock"],
  ["Kn1648", "Livestock"],
  ["Kn1121", "Livestock"],
  ["Kn1158", "Livestock"],
  ["Kn1094", "Livestock"],
  ["Kn1072", "Livestock"],
  ["Kn1076", "Livestock"],
  ["Kn943", "Livestock"],
  ["Kn5010", "Livestock"],
  ["Kn1061", "Livestock"],
  ["Kn852", "Agricultural Produce"],
  ["Kn668", "Agricultural Produce"],
  ["Kn777", "Agricultural Produce"],
  ["Kn820", "Agricultural Produce"],
  ["Py7", "Agricultural Produce"],
  ["Py50", "Agricultural Produce"],
  ["Kn5451", "Agricultural Produce"],
  ["My101", "Agricultural Produce"],
  ["Py20", "Agricultural Produce"],
  ["Kn856", "Agricultural Produce"],
  ["Kn415", "Agricultural Produce"],
  ["Kn427", "Agricultural Produce"],
  ["Kn1530", "Agricultural Produce"],
  ["Kn675", "Agricultural Produce"],
  ["Kn517", "Agricultural Produce"],
  ["My603", "Agricultural Produce"],
  ["My604", "Agricultural Produce"],
  ["My606", "Agricultural Produce"],
  ["Th65", "Agricultural Produce"],
  ["Th52", "Agricultural Produce"],
  ["Th55", "Agricultural Produce"],
  ["Py138", "Agricultural Produce"],
  ["Py2", "Agricultural Produce"],
  ["Py817", "Land Tenure"],
  ["Py782", "Land Tenure"],
  ["Py800", "Land Tenure"],
  ["Py71", "Land Tenure"],
  ["Py825", "Land Tenure"],
  ["Py824", "Land Tenure"],
  ["Py102", "Land Tenure"],
  ["Py259", "Land Tenure"],
  ["Py59", "Land Tenure"],
  ["Py609", "Land Tenure"],
  ["Py74", "Land Tenure"],
  ["Py659", "Land Tenure"],
  ["Py467", "Land Tenure"],
  ["Py211", "Land Tenure"],
  ["Py224", "Land Tenure"],
  ["Py276", "Land Tenure"],
  ["Py247", "Land Tenure"],
  ["Py160", "Land Tenure"],
  ["Py444", "Land Tenure"],
  ["Py351", "Land Tenure"],
  ["Py471", "Land Tenure"],
  ["Py281", "Land Tenure"],
  ["Py269", "Land Tenure"],
  ["Py278", "Land Tenure"],
  ["Py268", "Land Tenure"],
  ["Py371", "Land Tenure"],
  ["Py301", "Land Tenure"],
  ["Py818", "Land Tenure"],
  ["Py846", "Land Tenure"],
  ["Py895", "Land Tenure"],
  ["Py704", "Land Tenure"],
  ["Py294", "Land Tenure"],
  ["Py416", "Land Tenure"],
  ["Py409", "Land Tenure"],
  ["Py321", "Land Tenure"],
  ["Py297", "Land Tenure"],
  ["Py338", "Land Tenure"],
  ["Py705", "Land Tenure"],
  ["Py866", "Land Tenure"],
  ["Py473", "Land Tenure"],
  ["Py613", "Land Tenure"],
  ["Py842", "Land Tenure"],
  ["Py236", "Land Tenure"],
  ["Py317", "Land Tenure"],
  ["Py847", "Land Tenure"],
  ["Py901", "Land Tenure"],
  ["Py411", "Land Tenure"],
  ["Py36", "Land Tenure"],
  ["Py213", "Land Tenure"],
  ["Kn981", "Land Tenure"],
  ["Kn1031", "Land Tenure"],
  ["Kn835", "Land Tenure"],
  ["Kn836", "Land Tenure"],
  ["Kn839", "Land Tenure"],
  ["Kn983", "Land Tenure"],
  ["Kn863", "Land Tenure"],
  ["Kn862", "Land Tenure"],
  ["Kn841", "Land Tenure"],
  ["Th140", "Land Tenure"],
  ["Ti2", "Land Tenure"],
  ["Py650", "Dosmos Tablets"],
  ["Py644", "Dosmos Tablets"],
  ["Py646", "Dosmos Tablets"],
  ["Py649", "Dosmos Tablets"],
  ["Py312", "Dosmos Tablets"],
  ["Py880", "Dosmos Tablets"],
  ["Py718", "Dosmos Tablets"],
  ["Py90", "Taxation"],
  ["Py365", "Taxation"],
  ["Py330", "Taxation"],
  ["Py378", "Taxation"],
  ["Py225", "Taxation"],
  ["Py126", "Taxation"],
  ["Py222", "Taxation"],
  ["Py393", "Taxation"],
  ["Py123", "Taxation"],
  ["Py162", "Taxation"],
  ["Py456", "Taxation"],
  ["Py1396", "Taxation"],
  ["Py322", "Taxation"],
  ["Py543", "Taxation"],
  ["Py514", "Taxation"],
  ["Py245", "Taxation"],
  ["Py568", "Taxation"],
  ["Py248", "Taxation"],
  ["Py252", "Taxation"],
  ["Py520", "Taxation"],
  ["Py334", "Taxation"],
  ["Py926", "Taxation"],
  ["Py406", "Taxation"],
  ["Py831", "Taxation"],
  ["Py228", "Taxation"],
  ["Py319", "Taxation"],
  ["Py332", "Taxation"],
  ["Py608", "Taxation"],
  ["Py829", "Taxation"],
  ["Py438", "Taxation"],
  ["Kn4454", "Taxation"],
  ["Kn4455", "Taxation"],
  ["Kn4474", "Taxation"],
  ["Kn4484", "Taxation"],
  ["Kn5100", "Taxation"],
  ["Py310", "Industrial Production"],
  ["Py389", "Industrial Production"],
  ["Py658", "Industrial Production"],
  ["Py749", "Industrial Production"],
  ["Kn875", "Industrial Production"],
  ["Kn526", "Industrial Production"],
  ["Kn527", "Industrial Production"],
  ["Kn525", "Industrial Production"],
  ["Kn532", "Industrial Production"],
  ["Kn562", "Industrial Production"],
  ["Kn641", "Industrial Production"],
  ["Kn535", "Industrial Production"],
  ["Kn571", "Industrial Production"],
  ["Kn573", "Industrial Production"],
  ["Kn587", "Industrial Production"],
  ["Kn598", "Industrial Production"],
  ["Kn871", "Industrial Production"],
  ["Kn474", "Industrial Production"],
  ["Py594", "Industrial Production"],
  ["Py870", "Industrial Production"],
  ["Py647", "Industrial Production"],
  ["Py7377", "Industrial Production"],
  ["Py520", "Industrial Production"],
  ["Py683", "Industrial Production"],
  ["Py667", "Industrial Production"],
  ["Py693", "Industrial Production"],
  ["My110", "Industrial Production"],
  ["My129", "Industrial Production"],
  ["My111", "Industrial Production"],
  ["Th34", "Industrial Production"],
  ["Th36", "Industrial Production"],
  ["Py267", "Industrial Production"],
  ["Py249", "Industrial Production"],
  ["Py1184", "Industrial Production"],
  ["Py30", "Industrial Production"],
  ["Py1318", "Industrial Production"],
  ["Py10", "Industrial Production"],
  ["Kn4442", "Industrial Production"],
  ["Kn434", "Vessels and Furniture"],
  ["Kn740", "Vessels and Furniture"],
  ["Kn872", "Vessels and Furniture"],
  ["Kn160", "Vessels and Furniture"],
  ["Kn8497", "Vessels and Furniture"],
  ["My611", "Vessels and Furniture"],
  ["Py711", "Vessels and Furniture"],
  ["Py641", "Vessels and Furniture"],
  ["Py709", "Vessels and Furniture"],
  ["Py642", "Vessels and Furniture"],
  ["Py713", "Vessels and Furniture"],
  ["Py715", "Vessels and Furniture"],
  ["Py707", "Vessels and Furniture"],
  ["Py708", "Vessels and Furniture"],
  ["Py714", "Vessels and Furniture"],
  ["Py721", "Vessels and Furniture"],
  ["Py722", "Vessels and Furniture"],
  ["Py716", "Vessels and Furniture"],
  ["Py996", "Vessels and Furniture"],
  ["Kn1540", "Military Equipment"],
  ["Kn1548", "Military Equipment"],
  ["Kn984", "Military Equipment"],
  ["Kn1815", "Military Equipment"],
  ["Kn1704", "Military Equipment"],
  ["Kn4403", "Military Equipment"],
  ["Kn4401", "Military Equipment"],
  ["Kn4409", "Military Equipment"],
  ["Kn4413", "Military Equipment"],
  ["Kn4404", "Military Equipment"],
  ["Kn4402", "Military Equipment"],
  ["Kn4422", "Military Equipment"],
  ["Kn4420", "Military Equipment"],
  ["Kn4421", "Military Equipment"],
  ["Kn4428", "Military Equipment"],
  ["Kn879", "Military Equipment"],
  ["Kn891", "Military Equipment"],
  ["Kn1811", "Military Equipment"],
  ["Kn894", "Military Equipment"],
  ["Kn4437", "Military Equipment"],
  ["Kn4439", "Military Equipment"],
  ["Kn4440", "Military Equipment"],
  ["Kn4430", "Military Equipment"],
  ["Py487", "Military Equipment"],
  ["Py787", "Military Equipment"],
  ["Py793", "Military Equipment"],
  ["Py790", "Military Equipment"],
  ["Py682", "Military Equipment"],
  ["Py287", "Military Equipment"],
  ["Py1315", "Military Equipment"],
  ["Py737", "Military Equipment"],
  ["Py734", "Military Equipment"],
  ["Py740", "Military Equipment"],
  ["Py736", "Military Equipment"],
  ["Kn8100", "Military Equipment"],
  ["Ti5", "Military Equipment"],
  ["Kn222", "Military Equipment"],
  ["Kn226", "Military Equipment"],
  ["Py316", "Religion and Ritual"],
  ["Py6", "Religion and Ritual"],
  ["Py853", "Religion and Ritual"],
  ["Py1202", "Religion and Ritual"],
  ["Py1220", "Religion and Ritual"],
  ["Py1222", "Religion and Ritual"],
  ["Py1224", "Religion and Ritual"],
  ["Py1225", "Religion and Ritual"],
  ["Kn1", "Religion and Ritual"],
  ["Kn14", "Religion and Ritual"],
  ["Kn13", "Religion and Ritual"],
  ["Kn3", "Religion and Ritual"],
  ["Kn11", "Religion and Ritual"],
  ["Kn51", "Religion and Ritual"],
  ["Kn953", "Religion and Ritual"],
  ["Kn702", "Religion and Ritual"],
  ["Kn705", "Religion and Ritual"],
  ["Kn719", "Religion and Ritual"],
  ["Kn745", "Religion and Ritual"],
  ["Kn52", "Religion and Ritual"],
  ["Kh5", "Religion and Ritual"],
  ["Py187", "Religion and Ritual"],
  ["Th126", "Religion and Ritual"],
  ["Th130", "Religion and Ritual"],
  ["Th176", "Religion and Ritual"],
  ["Th164", "Religion and Ritual"],
  ["My701", "Religion and Ritual"],
  ["Py64", "Miscellaneous Texts"],
  ["Py218", "Miscellaneous Texts"],
  ["Py300", "Miscellaneous Texts"],
  ["Py1296", "Miscellaneous Texts"],
  ["Py1299", "Miscellaneous Texts"],
  ["Py1322", "Miscellaneous Texts"],
  ["Py482", "Miscellaneous Texts"],
  ["Py1324", "Miscellaneous Texts"],
  ["Py46", "Miscellaneous Texts"],
  ["Kn749", "Miscellaneous Texts"],
  ["Kn280", "Miscellaneous Texts"],
];

var tags = new Map();
for (var tag of tagValues) {
  if (tags.has(tag[0])) {
    tags.get(tag[0]).push(tag[1]);
    continue;
  }
  tags.set(tag[0], [tag[1]]);
}

